'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CorsoGreg_1

    Partial Public Class CronologiaSessioni
        Public Property IDSessione As Integer
        Public Property GuidSessione As System.Guid
        Public Property DataOraEsecuzione As Date
        Public Property TotaleErrori As Integer
        Public Property TotaleWarnings As Integer
        Public Property SavePath As String
    
        Public Overridable Property Logs As Logs
    
    End Class

End Namespace
