'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CorsoGreg_1

    Partial Public Class Logs
        Public Property IDLogTestata As Integer
        Public Property IDEsitoUltimaEsecuzione As Integer
        Public Property DataOraUltimaEsecuzione As Date
    
        Public Overridable Property CronologiaSessioni As ICollection(Of CronologiaSessioni) = New HashSet(Of CronologiaSessioni)
        Public Overridable Property Procedure As Procedure
    
    End Class

End Namespace
