'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace CorsoGreg_1

    Partial Public Class FrameworkEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=FrameworkEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property CronologiaSessioni() As DbSet(Of CronologiaSessioni)
        Public Overridable Property Logs() As DbSet(Of Logs)
        Public Overridable Property Direttive() As DbSet(Of Direttive)
        Public Overridable Property Procedure() As DbSet(Of Procedure)
    
    End Class

End Namespace
