'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CorsoGreg_1

    Partial Public Class Procedure
        Public Property id As Integer
        Public Property idCliente As Nullable(Of Integer)
        Public Property DescrizioneProgramma As String
        Public Property subdirectory As String
        Public Property DescrizioneAssembly As String
        Public Property annullato As Nullable(Of Integer)
        Public Property Note As String
        Public Property old_collegamento As String
        Public Property visibile As Nullable(Of Integer)
    
        Public Overridable Property Logs As ICollection(Of Logs) = New HashSet(Of Logs)
        Public Overridable Property Direttive As Direttive
    
    End Class

End Namespace
